clusterName: home-cluster
talosVersion: v1.0
endpoint: "https://192.168.200.10:6443"

nodes:
  - hostname: kmaster1
    ipAddress: 192.168.200.11
    installDisk: /dev/sda
    controlPlane: true
    domain: ""
  - hostname: kmaster2
    domain: ""
    ipAddress: 192.168.200.12
    installDisk: /dev/sda
    controlPlane: true
  - hostname: kworker1
    domain: ""
    ipAddress: 192.168.200.13
    installDisk: /dev/sdb
    controlPlane: false
controlplane:
  configPatches:
    - op: add
      path: /machine/kubelet/extraArgs
      value:
        rotate-server-certificates: "true"

worker:
  configPatches:
    - op: remove
      path: /machine
