name: test
on:
  push:
    branches:
      - master
    tags:
      - "*"
    paths:
      - 'main.go'
      - 'go.mod'
      - 'go.sum'
      - 'pkg/**'
      - 'cmd/**'
  pull_request:
    branches:
      - master
    paths:
      - 'main.go'
      - 'go.mod'
      - 'go.sum'
      - 'pkg/**'
      - 'cmd/**'
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - run: go build -o /usr/local/bin/talhelper
      - run: go test -v ./... -race -covermode=atomic
      - run: talhelper
