name: golangci-lint
on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - uses: actions/checkout@v3
      - run: go build
      - run: go test -v ./... -race -covermode=atomic
